### ISSUE TITLE
Github Repo's description is incorrect

### ISSUE THREAD

**Issue by MCF** [lvgl/lv_sim_visual_studio_sdl#17]
This project is now maintained with Visual Studio 2019.  The _About_ description still says Visual Studio 2017.

**Comment by MCF** [comment]
@kisvegabor can you please update the _About_ line and simply drop the 2017?  Or change to 2019 if you prefer.

**Comment by embeddedt** [comment]
Fixed. Do contributors not have the ability to change this?

**Comment by MCF** [comment]
No, no gear icon for me :-)

**Comment by kisvegabor** [comment]
@MCF I've changed your role from "Write" to "Maintain". Do you see the gear icon?

**Comment by MCF** [comment]
I can now see the gears and make those kinds of changes.  Thanks.

**Comment by MouriNaruto** [comment]
@kisvegabor I can't see the gear icon for me.

**Comment by kisvegabor** [comment]
@MouriNaruto it should work now.

**Comment by MouriNaruto** [comment]
> @MouriNaruto it should work now.

It works, thanks.
