### ISSUE TITLE
Need help update lvgl library to v7.0

### ISSUE THREAD

**Issue by summer666lyf** [lvgl/lv_sim_visual_studio_sdl#7]
I'm tried to build the example, but find this is lvglv6.0, can your update to v7.0?

**Comment by embeddedt** [comment]
See https://github.com/lvgl/lvgl/issues/1483#issuecomment-624429715

It will be updated soon.

**Comment by MCF** [comment]
This is in progress. waiting for a change to lvgl to be complete before it can be finished:

https://github.com/lvgl/lvgl/pull/1542

**Comment by DeonMarais64** [comment]
https://forum.lvgl.io/t/tft-simulator-on-visual-studio-2017-how-to-change-lvgl-from-v6-x-to-dev7-0/2263/7

**Comment by summer666lyf** [comment]
Hi all,
Thank  you for your support. The problem has been solved.

**Comment by MCF** [comment]
FWIW the lvgl visual studio compile errors have been fixed and this project has now been updated to work with the latest version of lvgl.

**Comment by kisvegabor** [comment]
Awesome! Thank you very much, Mike!
